version: '3'
services:
  oaienb:
    image: oaisoftwarealliance/oai-enb:develop
    container_name: oaienb
    stdin_open: true
    tty: true
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    devices:
      - "/dev/bus"
    volumes:
      - /dev/serial:/dev/serial:ro
      - /dev/bus/usb:/dev/bus/usb:ro
      - ./oai:/mnt/oai
      - ./oai/enb_entrypoint.sh:/opt/oai-enb/bin/entrypoint.sh:ro
      - ./log:/openairinterface5g/cmake_targets/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - USE_B2XX=1
    expose:
      - "36412/sctp"
      - "2152/udp"
    networks:
      default:
        ipv4_address: ${OAI_ENB_IP}
    command: ["/opt/oai-enb/bin/lte-softmodem", "-O", "/tmp/enb.conf"]
networks:
  default:
    external:
      name: docker_open5gs_pyhss_default
